-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2017.4 Schlumberger
-- User name   : user
-- Date        : Wednesday, January 04 2023 02:14:44
-- Project     : alyani_400134038.pet
-- Generated ]

INIT                                   -- Generated : Petrel

RPTINIT                                -- Generated : Petrel
  AREAX AREAY AREAZ BTOBALFV DIFFMX DIFFMY DIFFMZ DIFFMMF DIFFMX- DIFFMY- DIFFMZ- DZMTRXV IONROCK MULTPV MULTX MULTY MULTZ MULTX-
  MULTY- MULTZ- SIGMAGDV SIGMAV ROCKFRAC /

GRIDFILE                               -- Generated : Petrel
  0 0 /

GRIDUNIT                               -- Generated : Petrel
  FEET /

MAPUNITS                               -- Generated : Petrel
  FEET /

MAPAXES                                -- Generated : Petrel
  0 9000 0 10000 1000 10000 /

PINCH                                  -- Generated : Petrel
  1* 1* 1* 1* ALL /

