-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2017.4 Schlumberger
-- User name   : user
-- Date        : Wednesday, January 04 2023 02:14:45
-- Project     : alyani_400134038.pet
-- Generated ]

EQUIL                                  -- Generated : Petrel
          4700         4870         4900            0         4300            0 0 0 0 /

RPTSOL                                 -- Generated : Petrel
  PRES FIP=3 EQUIL RSVD RVVD AQUFET=2 APIVD ROCKMASS PRESD PWATD PGASD FIPVE OWC GOC SGCO TVDP SALTVD FIPTR=2 PBLK PLYADS RK ROCKC
  SURFBLK FIPSURF=2 TRADS PB PD FIPFOAM=2 FIPTEMP=2 POTC RECOV FLOOIL FLOWAT FLOGAS FIPRESV FLOSOL KRN QUIESC BFORG FFORG GASSATC
  THPRES CVOIL CVWAT CVSUR SME SIGM_MOD /

